### ISSUE TITLE
I should follow a style guide

### ISSUE THREAD

**Issue by colinrymer** [rentpath/open-source-template-js#3]
All of our open source JS libs should adhere to a style guide so that contributors know how things should be formatted. Ideally, there will be tooling available that programmatically ensures adherence to said style guide, especially by using other popular tooling (e.g. standard and eslint).

**Comment by colinrymer** [comment]
Currently, my preferred style guide/tooling is [standard](https://github.com/feross/standard) which uses [eslint](http://eslint.org/) under the hood.

**Comment by Teapane** [comment]
Colin, 'generator-node-module` is using `eslint`. I think we can close this.

**Comment by colinrymer** [comment]
I'd open an issue on it to switch to our style guide setup (which will use eslint)

**Comment by Teapane** [comment]
[Moved](https://github.com/rentpath/generator-node-module/issues/9)
