### ISSUE TITLE
I should write ES2015, ES7, etc. code that works in browsers without ES2015, ES7, etc. support.

### ISSUE THREAD

**Issue by colinrymer** [rentpath/open-source-template-js#4]

**Comment by martinstreicher** [comment]
Do we have a preferred pipeline? _babel_? _webpack_?

**Comment by colinrymer** [comment]
So webpack is just a tool for bundling modules, much like gulp, grunt, etc.

Babel is the tool we use for transpiling JS. It can be used as part of a module bundling pipeline (e.g. in webpack or gulp).

**Comment by Teapane** [comment]
[Moved](https://github.com/rentpath/generator-node-module/issues/5)
