### ISSUE TITLE
I should make code available via npm

### ISSUE THREAD

**Issue by martinstreicher** [rentpath/open-source-template-js#7]
Some of our public JS code will be consumed via Google Tag Manager tags and other conveniences by those who do not usually code. Nonetheless, all of the public JS code should be consumable via `package.json` and `npm`.

**Comment by martinstreicher** [comment]
One question. Should this repo be named `open-source-template.js`?

**Comment by Teapane** [comment]
[Moved](https://github.com/rentpath/generator-node-module/issues/6)
