### ISSUE TITLE
I should serve public JS code via a CDN

### ISSUE THREAD

**Issue by martinstreicher** [rentpath/open-source-template-js#9]
Google Tag Manager and other conveniences that consume the JS from us directly (as opposed to being bundled up via _webpack_ or the like, should pull the files from the CDN. Each public JS project should have a deploy script to copy the latest version of the code to the CDN.

**Comment by c0** [comment]
I think this should be the exception rather than a rule. We don't need to support serving JS over a CDN unless it's required. NPM is preferred. I think it should also be for internal use only rather than for public consumption.

**Comment by martinstreicher** [comment]
Yes, it is an exception.

**Comment by martinstreicher** [comment]
It is an exception, but I wonder if the template should comprehend it since it is a template, a kind of superset of things that need to be done. Projects could strip out anything optional, such as this exception if it did not apply. Of course, this may not be needed at all in a project if the CDN-related piece(s) are strictly found in Travis or another system that is customized separately. I'll leave this for now until we resolve it.

**Comment by Teapane** [comment]
@colinrymer thoughts on this? Should I port a similar issue over to the generator repo?

**Comment by colinrymer** [comment]
Yeah, let's add an issue to discuss publishing to CDN, etc.

**Comment by Teapane** [comment]
[Moved](https://github.com/rentpath/generator-node-module/issues/8)
